;; Olabit fungible token (manual implementation)
;; Simple admin-controlled token with one-time initializer

(define-data-var initialized bool false)
(define-data-var admin (optional principal) none)
(define-data-var total-supply uint u0)
(define-map balances principal uint)

(define-constant ERR_ALREADY_INITIALIZED u100)
(define-constant ERR_NOT_ADMIN u101)
(define-constant ERR_INSUFFICIENT_BAL u102)
(define-constant ERR_ZERO_AMOUNT u103)

(define-read-only (get-name) "Olabit")
(define-read-only (get-symbol) "OLAB")
(define-read-only (get-decimals) u6)
(define-read-only (get-total-supply) (var-get total-supply))
(define-read-only (get-balance (who principal))
  (default-to u0 (map-get? balances who))
)
(define-read-only (get-admin) (var-get admin))
(define-read-only (is-initialized) (var-get initialized))

(define-private (is-admin (who principal))
  (is-eq (var-get admin) (some who))
)

(define-private (add-balance (who principal) (amount uint))
  (let ((old (default-to u0 (map-get? balances who))))
    (map-set balances who (+ old amount))
  )
)

(define-private (sub-balance (who principal) (amount uint))
  (let ((old (default-to u0 (map-get? balances who))))
    (if (>= old amount)
        (begin
          (map-set balances who (- old amount))
          (ok true)
        )
        (err ERR_INSUFFICIENT_BAL)
    )
  )
)

(define-public (initialize (new-admin principal) (initial-supply uint))
  (begin
    (if (var-get initialized)
        (err ERR_ALREADY_INITIALIZED)
        (begin
          (var-set admin (some new-admin))
          (var-set initialized true)
          (if (> initial-supply u0)
              (begin
                (add-balance new-admin initial-supply)
                (var-set total-supply (+ (var-get total-supply) initial-supply))
                (ok true)
              )
              (ok true)
          )
        )
    )
  )
)

(define-public (mint (amount uint) (recipient principal))
  (if (is-admin tx-sender)
      (if (> amount u0)
          (begin
            (add-balance recipient amount)
            (var-set total-supply (+ (var-get total-supply) amount))
            (ok true)
          )
          (err ERR_ZERO_AMOUNT)
      )
      (err ERR_NOT_ADMIN)
  )
)

(define-public (burn (amount uint))
  (if (> amount u0)
      (match (sub-balance tx-sender amount)
        okv (begin
               (var-set total-supply (- (var-get total-supply) amount))
               (ok true)
             )
        errv (err errv)
      )
      (err ERR_ZERO_AMOUNT)
  )
)

(define-public (transfer (amount uint) (recipient principal))
  (if (> amount u0)
      (match (sub-balance tx-sender amount)
        okv (begin (add-balance recipient amount) (ok true))
        errv (err errv)
      )
      (err ERR_ZERO_AMOUNT)
  )
)
